### ISSUE TITLE
Nubia fails for long texts

### ISSUE THREAD

**Issue by tuetschek** [GEM-benchmark/GEM-metrics#42]
@aliabd In general NUBIA seems to work OK (though slow), but it fails if the input text is too long (>512 tokens):
```
Traceback (most recent call last):
  File "./run_metrics.py", line 7, in <module>
    gem_metrics.main()
  File "/lnet/spec/work/people/odusek/gem-metrics/gem_metrics/__init__.py", line 311, in main
    process_files(config)
  File "/lnet/spec/work/people/odusek/gem-metrics/gem_metrics/__init__.py", line 259, in process_files
    values = process_submission(data, ref_data, src_data, metric_dict)
  File "/lnet/spec/work/people/odusek/gem-metrics/gem_metrics/__init__.py", line 144, in process_submission
    values[dataset] = compute(outs_ds, refs_ds, srcs_ds, metrics_dict=metrics_dict)
  File "/lnet/spec/work/people/odusek/gem-metrics/gem_metrics/__init__.py", line 112, in compute
    values.update(metric.compute(outs, refs))
  File "/lnet/spec/work/people/odusek/gem-metrics/gem_metrics/nubia.py", line 19, in compute
    mutli_scores.append(self.metric.score(_ref, pred))
  File "/lnet/spec/work/people/odusek/gem-metrics/venv_gem/lib/python3.6/site-packages/nubia_score/nubia.py", line 191, in score
    aggregator=aggregator, gpt_ref=gpt_ref)
  File "/lnet/spec/work/people/odusek/gem-metrics/venv_gem/lib/python3.6/site-packages/nubia_score/nubia.py", line 120, in nubia
    sim = float(self._roberta_similarity(tokens)[0])
  File "/lnet/spec/work/people/odusek/gem-metrics/venv_gem/lib/python3.6/site-packages/nubia_score/nubia.py", line 97, in _roberta_similarity
    features = self.roberta_STS.extract_features(tokens)
  File "/lnet/spec/work/people/odusek/gem-metrics/venv_gem/lib/python3.6/site-packages/fairseq/models/roberta/hub_interface.py", line 90, in extract_features
    tokens.size(-1), self.model.max_positions()
ValueError: tokens exceeds maximum length: 522 > 512
```
Could you please make it not crash? Not sure if this needs to be solved here or within NUBIA itself.

**Comment by aliabd** [comment]
Will fix from NUBIA's side

**Comment by aliabd** [comment]
Just pushed a fix (truncating the tokens now, like bert score and others). Please update the `nubia-score` package to latest (`0.1.5`). Let me know if you still have issues. 

Sorry about the sluggishness, we still have a ways to go to give the library better performance.

**Comment by tuetschek** [comment]
Seems to be working, thanks! 

Due to the speed, I'll probably exclude NUBIA even from `--heavy-metrics` by default for now. It will still be possible to trigger it using `--metric-list`. Hope that's OK.

**Comment by hassan-medium** [comment]
Hi @tuetschek, what does that mean as far as the Shared Task at the GEM Workshop at ACL 2021 goes?

Will the output of NUBIA on submissions be given to participants for system analysis?

**Comment by mhkane** [comment]
Hi @tuetschek, what does that mean as far as the Shared Task at the GEM Workshop at ACL 2021 goes?

Will the output of NUBIA on submissions be given/available to participants for system/metric analysis?

**Comment by mhkane** [comment]
Hi @tuetschek, what does that mean as far as the Evaluation task at the GEM Workshop at ACL 2021 goes?

Will the output of NUBIA on submissions be given/available to participants for system/metric analysis?

**Comment by tuetschek** [comment]
I guess that's not really a question for me but for @sebastianGehrmann probably. The default setting of the switches doesn't determine what GEM will include. 

As far as it concerns me, I'm happy to run it, but it takes way longer than anything else, so whether I'll be able to run it or not depends on timing. I have some baseline mT5 results from @sebastianGehrmann on multiple datasets. Without NUBIA (and including BERTScore and BLEURT), these take ~2-3 hours to compute (on CPU, since the different metrics clash on a GPU). With NUBIA, I started the computation more than 3 days ago and it's still running. I guess I can try to run NUBIA separately on a GPU and see if that's any faster.

**Comment by mhkane** [comment]
Yes, GPU should help and for this initial shared task, we're also happy to help with evaluation. 

Let us know how we can help. It would mean a lot to have our evaluation outputs be analyzed!
