### ISSUE TITLE
Cannot run example command with example data

### ISSUE THREAD

**Issue by lxuechen** [GEM-benchmark/GEM-metrics#51]
After cloning repo and installing requirements, running the following given example fails
```bash
./run_metrics.py test_data/single_dataset.outs.json -r test_data/single_dataset.refs.json
```

```shell
Traceback (most recent call last):
  File "./run_metrics.py", line 7, in <module>
    gem_metrics.main()
  File "/Users/xuechenli/remote/GEM-metrics/gem_metrics/__init__.py", line 543, in main
    process_files(config)
  File "/Users/xuechenli/remote/GEM-metrics/gem_metrics/__init__.py", line 439, in process_files
    refs = References(config.references_file)
  File "/Users/xuechenli/remote/GEM-metrics/gem_metrics/texts.py", line 149, in __init__
    super().__init__(data_key="target", data=data, language=language)
  File "/Users/xuechenli/remote/GEM-metrics/gem_metrics/texts.py", line 39, in __init__
    if isinstance(self.all_data[0], str):
KeyError: 0
```

**Comment by ashleylew** [comment]
I'm getting this same error.
